version: '3.9'
services:
  db:
    image: mariadb:latest
    container_name: crm-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER={$DB_USERNAME}
      - MYSQL_PASSWORD={$DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    links:
      - php

volumes:
  mysql-data:
