version: '3.9'
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: crm-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
