# sudo docker-compose up -d
version: "3.9"
services:
  php:
    #image: php:8.3-fpm
    build: './etc/infrastructure/php'
    container_name: crm-php
    user: "www-data:www-data"
    volumes:
    - ./etc/.bashrc:/root/.bashrc
    - ./etc/.bashrc:/home/www-data/.bashrc
    - .:/var/www/crm/
    - ./bootstrap/cache/:/var/www/crm/bootstrap/cache/
    #- ./etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www/crm/
    links:
    - cache
    ports:
      - "9003:9003"
  web:
    #image: nginx:stable
    build: './etc/infrastructure/nginx'
    container_name: crm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./etc/.bashrc:/home/www-data/.bashrc
    - .:/var/www/crm/
    - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./etc/infrastructure/nginx/static.conf:/etc/nginx/conf.d/static.conf
    - ./etc/infrastructure/nginx/ssl/:/etc/ssl/
    - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d/
    links:
    - cache
    - php
    depends_on:
    - php
  cache:
    image: redis
    container_name: crm-cache
    ports:
      - "6379:6379"
    volumes:
      - ./etc/infrastructure/redis/redis.conf:/etc/redis/redis.conf
