version: '3.9'
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: crm-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: $DB_PASSWORD
    ports:
      - "5050:80"
    depends_on:
      - db
